

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Отсутствует описание модели
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class LogMatsAndGoodsQuantitiesItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Инициализирует новый экземпляр сущности LogMatsAndGoodsQuantitiesItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LogMatsAndGoodsQuantitiesItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LogMatsAndGoodsQuantitiesItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LogMatsAndGoodsQuantitiesItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LogMatsAndGoodsQuantitiesItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Получает объект Application для данного приложения.  Объект Application предоставляет доступ к активным экранам, методы для открытых экранов и доступ к текущему пользователю.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Получает вмещающую рабочую область данных.  Рабочая область данных предоставляет доступ ко всем источникам данных в приложении.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ID
        {
            get
            {
                return global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> c_Date
        {
            get
            {
                return global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.c_Date);
            }
            set
            {
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.c_Date, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Quantity
        {
            get
            {
                return global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.Quantity);
            }
            set
            {
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.Quantity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.MatsAndGoodsItem MatsAndGoodsItem
        {
            get
            {
                return global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem);
            }
            set
            {
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.SkladiItem SkladiItem
        {
            get
            {
                return global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.GetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.SkladiItem);
            }
            set
            {
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.SetValue(this, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.SkladiItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkladiItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkladiItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkladiItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem,
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass,
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass>.Entry
                __LogMatsAndGoodsQuantitiesItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.__LogMatsAndGoodsQuantitiesItem_CreateNew,
                    global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.__LogMatsAndGoodsQuantitiesItem_Created,
                    global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.__LogMatsAndGoodsQuantitiesItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem __LogMatsAndGoodsQuantitiesItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem> es)
            {
                return new global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem(es);
            }
            private static void __LogMatsAndGoodsQuantitiesItem_Created(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
            {
                e.LogMatsAndGoodsQuantitiesItem_Created();
            }
            private static bool __LogMatsAndGoodsQuantitiesItem_AllowSaveWithErrors(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
            {
                bool result = false;
                e.LogMatsAndGoodsQuantitiesItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, decimal> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<global::System.DateTime>> c_Date
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.c_Date) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<decimal>> Quantity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.Quantity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem> MatsAndGoodsItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.SkladiItem> SkladiItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.SkladiItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.SkladiItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new decimal ID { get; }
                new global::System.Nullable<global::System.DateTime> c_Date { get; set; }
                new global::System.Nullable<decimal> Quantity { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation MatsAndGoodsItem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation SkladiItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, decimal>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, decimal>.Entry(
                        "ID",
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static decimal _ID_GetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    c_Date = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "c_Date",
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._c_Date_Stub,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._c_Date_ComputeIsReadOnly,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._c_Date_Validate,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._c_Date_GetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._c_Date_SetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._c_Date_OnValueChanged);
                private static void _c_Date_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Date, sf);
                }
                private static bool _c_Date_ComputeIsReadOnly(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    bool result = false;
                    e.c_Date_IsReadOnly(ref result);
                    return result;
                }
                private static void _c_Date_Validate(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.c_Date_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _c_Date_GetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.c_Date;
                }
                private static void _c_Date_SetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.c_Date = global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _c_Date_OnValueChanged(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    e.c_Date_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Quantity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Quantity",
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._Quantity_Stub,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._Quantity_ComputeIsReadOnly,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._Quantity_Validate,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._Quantity_GetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._Quantity_SetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._Quantity_OnValueChanged);
                private static void _Quantity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity, sf);
                }
                private static bool _Quantity_ComputeIsReadOnly(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    bool result = false;
                    e.Quantity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity_Validate(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity_Validate(r);
                }
                private static global::System.Nullable<decimal> _Quantity_GetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity;
                }
                private static void _Quantity_SetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Quantity = v;
                }
                private static void _Quantity_OnValueChanged(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    e.Quantity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Entry
                    MatsAndGoodsItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Entry(
                        "MatsAndGoodsItem",
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Stub,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Validate,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_GetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_SetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Refresh,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_OnValueChanged);
                private static void _MatsAndGoodsItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Data> c, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MatsAndGoodsItem, sf);
                }
                private static bool _MatsAndGoodsItem_ComputeIsReadOnly(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    bool result = false;
                    e.MatsAndGoodsItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _MatsAndGoodsItem_Validate(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MatsAndGoodsItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _MatsAndGoodsItem_GetCoreImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MatsAndGoodsItem;
                }
                private static global::LightSwitchApplication.MatsAndGoodsItem _MatsAndGoodsItem_GetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.MatsAndGoodsItem, global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass>(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem);
                }
                private static void _MatsAndGoodsItem_SetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, global::LightSwitchApplication.MatsAndGoodsItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem, (i, ev) => i.MatsAndGoodsItem = ev, v);
                }
                private static void _MatsAndGoodsItem_Refresh(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem);
                }
                private static void _MatsAndGoodsItem_OnValueChanged(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    e.MatsAndGoodsItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Entry
                    SkladiItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Entry(
                        "SkladiItem",
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_Stub,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_Validate,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_GetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_SetImplementationValue,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_Refresh,
                        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties._SkladiItem_OnValueChanged);
                private static void _SkladiItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Data> c, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, object sf)
                {
                    c(d, ref d._SkladiItem, sf);
                }
                private static bool _SkladiItem_ComputeIsReadOnly(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    bool result = false;
                    e.SkladiItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _SkladiItem_Validate(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SkladiItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _SkladiItem_GetCoreImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    return d.ImplementationEntity.SkladiItem;
                }
                private static global::LightSwitchApplication.SkladiItem _SkladiItem_GetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.SkladiItem, global::LightSwitchApplication.SkladiItem.DetailsClass>(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.SkladiItem, ref d._SkladiItem);
                }
                private static void _SkladiItem_SetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d, global::LightSwitchApplication.SkladiItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.SkladiItem, ref d._SkladiItem, (i, ev) => i.SkladiItem = ev, v);
                }
                private static void _SkladiItem_Refresh(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.PropertySetProperties.SkladiItem, ref d._SkladiItem);
                }
                private static void _SkladiItem_OnValueChanged(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem e)
                {
                    e.SkladiItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, decimal>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _c_Date;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::System.Nullable<decimal>>.Data _Quantity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Data _MatsAndGoodsItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem, global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Data _SkladiItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
