

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Отсутствует описание модели
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class CraftFillerItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Инициализирует новый экземпляр сущности CraftFillerItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CraftFillerItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CraftFillerItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CraftFillerItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CraftFillerItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftFillerItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftFillerItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Получает объект Application для данного приложения.  Объект Application предоставляет доступ к активным экранам, методы для открытых экранов и доступ к текущему пользователю.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Получает вмещающую рабочую область данных.  Рабочая область данных предоставляет доступ ко всем источникам данных в приложении.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ID
        {
            get
            {
                return global::LightSwitchApplication.CraftFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Quantity
        {
            get
            {
                return global::LightSwitchApplication.CraftFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity);
            }
            set
            {
                global::LightSwitchApplication.CraftFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Quantity1
        {
            get
            {
                return global::LightSwitchApplication.CraftFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity1);
            }
            set
            {
                global::LightSwitchApplication.CraftFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity1_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Quantity2
        {
            get
            {
                return global::LightSwitchApplication.CraftFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity2);
            }
            set
            {
                global::LightSwitchApplication.CraftFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity2, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity2_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity2_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity2_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.MatsAndGoodsItem MatsAndGoodsItem
        {
            get
            {
                return global::LightSwitchApplication.CraftFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem);
            }
            set
            {
                global::LightSwitchApplication.CraftFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.CraftActionItem CraftActionItem
        {
            get
            {
                return global::LightSwitchApplication.CraftFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.CraftActionItem);
            }
            set
            {
                global::LightSwitchApplication.CraftFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.CraftActionItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftActionItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftActionItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftActionItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CraftFillerItem,
                global::LightSwitchApplication.CraftFillerItem.DetailsClass,
                global::LightSwitchApplication.CraftFillerItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass>.Entry
                __CraftFillerItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.CraftFillerItem.DetailsClass.__CraftFillerItem_CreateNew,
                    global::LightSwitchApplication.CraftFillerItem.DetailsClass.__CraftFillerItem_Created,
                    global::LightSwitchApplication.CraftFillerItem.DetailsClass.__CraftFillerItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CraftFillerItem __CraftFillerItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CraftFillerItem> es)
            {
                return new global::LightSwitchApplication.CraftFillerItem(es);
            }
            private static void __CraftFillerItem_Created(global::LightSwitchApplication.CraftFillerItem e)
            {
                e.CraftFillerItem_Created();
            }
            private static bool __CraftFillerItem_AllowSaveWithErrors(global::LightSwitchApplication.CraftFillerItem e)
            {
                bool result = false;
                e.CraftFillerItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, decimal> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>> Quantity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>> Quantity1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>> Quantity2
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.Quantity2) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem> MatsAndGoodsItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.CraftActionItem> CraftActionItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.CraftActionItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new decimal ID { get; }
                new global::System.Nullable<decimal> Quantity { get; set; }
                new global::System.Nullable<decimal> Quantity1 { get; set; }
                new global::System.Nullable<decimal> Quantity2 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation MatsAndGoodsItem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation CraftActionItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, decimal>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, decimal>.Entry(
                        "ID",
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.CraftFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.CraftFillerItem e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.CraftFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static decimal _ID_GetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.CraftFillerItem e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Quantity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Quantity",
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity_Stub,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity_Validate,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity_GetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity_SetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity_OnValueChanged);
                private static void _Quantity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.CraftFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity, sf);
                }
                private static bool _Quantity_ComputeIsReadOnly(global::LightSwitchApplication.CraftFillerItem e)
                {
                    bool result = false;
                    e.Quantity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity_Validate(global::LightSwitchApplication.CraftFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity_Validate(r);
                }
                private static global::System.Nullable<decimal> _Quantity_GetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity;
                }
                private static void _Quantity_SetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Quantity = v;
                }
                private static void _Quantity_OnValueChanged(global::LightSwitchApplication.CraftFillerItem e)
                {
                    e.Quantity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Quantity1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Quantity1",
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity1_Stub,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity1_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity1_Validate,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity1_GetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity1_SetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity1_OnValueChanged);
                private static void _Quantity1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.CraftFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity1, sf);
                }
                private static bool _Quantity1_ComputeIsReadOnly(global::LightSwitchApplication.CraftFillerItem e)
                {
                    bool result = false;
                    e.Quantity1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity1_Validate(global::LightSwitchApplication.CraftFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity1_Validate(r);
                }
                private static global::System.Nullable<decimal> _Quantity1_GetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity1;
                }
                private static void _Quantity1_SetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Quantity1 = v;
                }
                private static void _Quantity1_OnValueChanged(global::LightSwitchApplication.CraftFillerItem e)
                {
                    e.Quantity1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Quantity2 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Quantity2",
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity2_Stub,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity2_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity2_Validate,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity2_GetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity2_SetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._Quantity2_OnValueChanged);
                private static void _Quantity2_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.CraftFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity2, sf);
                }
                private static bool _Quantity2_ComputeIsReadOnly(global::LightSwitchApplication.CraftFillerItem e)
                {
                    bool result = false;
                    e.Quantity2_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity2_Validate(global::LightSwitchApplication.CraftFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity2_Validate(r);
                }
                private static global::System.Nullable<decimal> _Quantity2_GetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity2;
                }
                private static void _Quantity2_SetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Quantity2 = v;
                }
                private static void _Quantity2_OnValueChanged(global::LightSwitchApplication.CraftFillerItem e)
                {
                    e.Quantity2_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Entry
                    MatsAndGoodsItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Entry(
                        "MatsAndGoodsItem",
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Stub,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Validate,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_GetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_SetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Refresh,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_OnValueChanged);
                private static void _MatsAndGoodsItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Data> c, global::LightSwitchApplication.CraftFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MatsAndGoodsItem, sf);
                }
                private static bool _MatsAndGoodsItem_ComputeIsReadOnly(global::LightSwitchApplication.CraftFillerItem e)
                {
                    bool result = false;
                    e.MatsAndGoodsItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _MatsAndGoodsItem_Validate(global::LightSwitchApplication.CraftFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MatsAndGoodsItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _MatsAndGoodsItem_GetCoreImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MatsAndGoodsItem;
                }
                private static global::LightSwitchApplication.MatsAndGoodsItem _MatsAndGoodsItem_GetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.MatsAndGoodsItem, global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass>(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem);
                }
                private static void _MatsAndGoodsItem_SetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d, global::LightSwitchApplication.MatsAndGoodsItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem, (i, ev) => i.MatsAndGoodsItem = ev, v);
                }
                private static void _MatsAndGoodsItem_Refresh(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem);
                }
                private static void _MatsAndGoodsItem_OnValueChanged(global::LightSwitchApplication.CraftFillerItem e)
                {
                    e.MatsAndGoodsItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Entry
                    CraftActionItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Entry(
                        "CraftActionItem",
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_Stub,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_Validate,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_GetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_SetImplementationValue,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_Refresh,
                        global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties._CraftActionItem_OnValueChanged);
                private static void _CraftActionItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Data> c, global::LightSwitchApplication.CraftFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CraftActionItem, sf);
                }
                private static bool _CraftActionItem_ComputeIsReadOnly(global::LightSwitchApplication.CraftFillerItem e)
                {
                    bool result = false;
                    e.CraftActionItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _CraftActionItem_Validate(global::LightSwitchApplication.CraftFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CraftActionItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _CraftActionItem_GetCoreImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CraftActionItem;
                }
                private static global::LightSwitchApplication.CraftActionItem _CraftActionItem_GetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.CraftActionItem, global::LightSwitchApplication.CraftActionItem.DetailsClass>(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.CraftActionItem, ref d._CraftActionItem);
                }
                private static void _CraftActionItem_SetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass d, global::LightSwitchApplication.CraftActionItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.CraftActionItem, ref d._CraftActionItem, (i, ev) => i.CraftActionItem = ev, v);
                }
                private static void _CraftActionItem_Refresh(global::LightSwitchApplication.CraftFillerItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CraftFillerItem.DetailsClass.PropertySetProperties.CraftActionItem, ref d._CraftActionItem);
                }
                private static void _CraftActionItem_OnValueChanged(global::LightSwitchApplication.CraftFillerItem e)
                {
                    e.CraftActionItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, decimal>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data _Quantity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data _Quantity1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data _Quantity2;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Data _MatsAndGoodsItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftFillerItem, global::LightSwitchApplication.CraftFillerItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Data _CraftActionItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
