

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Отсутствует описание модели
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class ResponsibleItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Инициализирует новый экземпляр сущности ResponsibleItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ResponsibleItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ResponsibleItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ResponsibleItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ResponsibleItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponsibleItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResponsibleItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Получает объект Application для данного приложения.  Объект Application предоставляет доступ к активным экранам, методы для открытых экранов и доступ к текущему пользователю.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Получает вмещающую рабочую область данных.  Рабочая область данных предоставляет доступ ко всем источникам данных в приложении.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ID
        {
            get
            {
                return global::LightSwitchApplication.ResponsibleItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.ResponsibleItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.ResponsibleItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Note
        {
            get
            {
                return global::LightSwitchApplication.ResponsibleItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.Note);
            }
            set
            {
                global::LightSwitchApplication.ResponsibleItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.Note, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Note_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Note_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Note_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.CraftActionItem> CraftAction
        {
            get
            {
                return global::LightSwitchApplication.ResponsibleItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.CraftAction);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.CraftActionItem> CraftActionQuery
        {
            get
            {
                return global::LightSwitchApplication.ResponsibleItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.CraftAction);
            }
        }

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.SkladiItem SkladiItem
        {
            get
            {
                return global::LightSwitchApplication.ResponsibleItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.SkladiItem);
            }
            set
            {
                global::LightSwitchApplication.ResponsibleItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.SkladiItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkladiItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkladiItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkladiItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ResponsibleItem,
                global::LightSwitchApplication.ResponsibleItem.DetailsClass,
                global::LightSwitchApplication.ResponsibleItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass>.Entry
                __ResponsibleItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.ResponsibleItem.DetailsClass.__ResponsibleItem_CreateNew,
                    global::LightSwitchApplication.ResponsibleItem.DetailsClass.__ResponsibleItem_Created,
                    global::LightSwitchApplication.ResponsibleItem.DetailsClass.__ResponsibleItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ResponsibleItem __ResponsibleItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ResponsibleItem> es)
            {
                return new global::LightSwitchApplication.ResponsibleItem(es);
            }
            private static void __ResponsibleItem_Created(global::LightSwitchApplication.ResponsibleItem e)
            {
                e.ResponsibleItem_Created();
            }
            private static bool __ResponsibleItem_AllowSaveWithErrors(global::LightSwitchApplication.ResponsibleItem e)
            {
                bool result = false;
                e.ResponsibleItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, decimal> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string> Note
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.Note) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.CraftActionItem> CraftAction
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.CraftAction) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.SkladiItem> SkladiItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.SkladiItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.SkladiItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new decimal ID { get; }
                new string Name { get; set; }
                new string Note { get; set; }
                new global::System.Collections.IEnumerable CraftAction { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation SkladiItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, decimal>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, decimal>.Entry(
                        "ID",
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.ResponsibleItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.ResponsibleItem e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.ResponsibleItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static decimal _ID_GetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.ResponsibleItem e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.ResponsibleItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.ResponsibleItem e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.ResponsibleItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.ResponsibleItem e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Entry
                    Note = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Entry(
                        "Note",
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Note_Stub,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Note_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Note_Validate,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Note_GetImplementationValue,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Note_SetImplementationValue,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._Note_OnValueChanged);
                private static void _Note_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.ResponsibleItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Note, sf);
                }
                private static bool _Note_ComputeIsReadOnly(global::LightSwitchApplication.ResponsibleItem e)
                {
                    bool result = false;
                    e.Note_IsReadOnly(ref result);
                    return result;
                }
                private static void _Note_Validate(global::LightSwitchApplication.ResponsibleItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Note_Validate(r);
                }
                private static string _Note_GetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Note;
                }
                private static void _Note_SetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Note = v;
                }
                private static void _Note_OnValueChanged(global::LightSwitchApplication.ResponsibleItem e)
                {
                    e.Note_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Entry
                    CraftAction = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Entry(
                        "CraftAction",
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._CraftAction_Stub,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._CraftAction_GetReferencedEntities,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._CraftAction_GetEntityCollection);
                private static void _CraftAction_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Data> c, global::LightSwitchApplication.ResponsibleItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CraftAction, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.CraftActionItem> _CraftAction_GetReferencedEntities(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.CraftActionItem, global::LightSwitchApplication.CraftActionItem.DetailsClass>(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.CraftAction, ref d._CraftAction);
                }
                private static global::System.Collections.IEnumerable _CraftAction_GetEntityCollection(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CraftAction;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Entry
                    SkladiItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Entry(
                        "SkladiItem",
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_Stub,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_Validate,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_GetImplementationValue,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_SetImplementationValue,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_Refresh,
                        global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties._SkladiItem_OnValueChanged);
                private static void _SkladiItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Data> c, global::LightSwitchApplication.ResponsibleItem.DetailsClass d, object sf)
                {
                    c(d, ref d._SkladiItem, sf);
                }
                private static bool _SkladiItem_ComputeIsReadOnly(global::LightSwitchApplication.ResponsibleItem e)
                {
                    bool result = false;
                    e.SkladiItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _SkladiItem_Validate(global::LightSwitchApplication.ResponsibleItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SkladiItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _SkladiItem_GetCoreImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    return d.ImplementationEntity.SkladiItem;
                }
                private static global::LightSwitchApplication.SkladiItem _SkladiItem_GetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.SkladiItem, global::LightSwitchApplication.SkladiItem.DetailsClass>(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.SkladiItem, ref d._SkladiItem);
                }
                private static void _SkladiItem_SetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass d, global::LightSwitchApplication.SkladiItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.SkladiItem, ref d._SkladiItem, (i, ev) => i.SkladiItem = ev, v);
                }
                private static void _SkladiItem_Refresh(global::LightSwitchApplication.ResponsibleItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ResponsibleItem.DetailsClass.PropertySetProperties.SkladiItem, ref d._SkladiItem);
                }
                private static void _SkladiItem_OnValueChanged(global::LightSwitchApplication.ResponsibleItem e)
                {
                    e.SkladiItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, decimal>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, string>.Data _Note;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Data _CraftAction;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ResponsibleItem, global::LightSwitchApplication.ResponsibleItem.DetailsClass, global::LightSwitchApplication.SkladiItem>.Data _SkladiItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
