//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region ActionsItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ActionsItem :
        global::LightSwitchApplication.ActionsItem.DetailsClass.IImplementation
    {
        partial void OnFromSkladIDChanged()
        {
            this.___OnPropertyChanged("FromSkladID");
            this.___OnPropertyChanged("SkladiItem");
        }
        
        partial void OnToSkladIDChanged()
        {
            this.___OnPropertyChanged("ToSkladID");
            this.___OnPropertyChanged("SkladiItem1");
        }
        
        partial void OnSupplierIDChanged()
        {
            this.___OnPropertyChanged("SupplierID");
            this.___OnPropertyChanged("SuppliersItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnActionChanged()
        {
            this.___OnPropertyChanged("Action");
        }
        
        partial void OnCreationDateChanged()
        {
            this.___OnPropertyChanged("CreationDate");
        }
        
        partial void OnRealiationDateChanged()
        {
            this.___OnPropertyChanged("RealiationDate");
        }
        
        partial void OnRealTimeCreationDateChanged()
        {
            this.___OnPropertyChanged("RealTimeCreationDate");
        }
        
        partial void OnNoteChanged()
        {
            this.___OnPropertyChanged("Note");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnPriceChanged()
        {
            this.___OnPropertyChanged("Price");
        }
        
        partial void OnNumberChanged()
        {
            this.___OnPropertyChanged("Number");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ActionsItem.DetailsClass.IImplementation.SkladiItem
        {
            get
            {
                return this.SkladiItem;
            }
            set
            {
                this.SkladiItem = (global::LightSwitchApplication.Implementation.SkladiItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> __SkladiItem
        {
            get
            {
                if (this.___SkladiItem == null)
                {
                    this.___SkladiItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem>(
                        this,
                        "SkladiItem",
                        new string[] { "FromSkladID" },
                        e => global::System.Object.Equals(e.ID, this.FromSkladID),
                        () => this._SkladiItem,
                        e => this._SkladiItem = e);
                }
                return this.___SkladiItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> ___SkladiItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ActionsItem.DetailsClass.IImplementation.SkladiItem1
        {
            get
            {
                return this.SkladiItem1;
            }
            set
            {
                this.SkladiItem1 = (global::LightSwitchApplication.Implementation.SkladiItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> __SkladiItem1
        {
            get
            {
                if (this.___SkladiItem1 == null)
                {
                    this.___SkladiItem1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem>(
                        this,
                        "SkladiItem1",
                        new string[] { "ToSkladID" },
                        e => global::System.Object.Equals(e.ID, this.ToSkladID),
                        () => this._SkladiItem1,
                        e => this._SkladiItem1 = e);
                }
                return this.___SkladiItem1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> ___SkladiItem1;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ActionsItem.DetailsClass.IImplementation.SuppliersItem
        {
            get
            {
                return this.SuppliersItem;
            }
            set
            {
                this.SuppliersItem = (global::LightSwitchApplication.Implementation.SuppliersItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SuppliersItem> __SuppliersItem
        {
            get
            {
                if (this.___SuppliersItem == null)
                {
                    this.___SuppliersItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SuppliersItem>(
                        this,
                        "SuppliersItem",
                        new string[] { "SupplierID" },
                        e => global::System.Object.Equals(e.ID, this.SupplierID),
                        () => this._SuppliersItem,
                        e => this._SuppliersItem = e);
                }
                return this.___SuppliersItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SuppliersItem> ___SuppliersItem;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActionsItem.DetailsClass.IImplementation.ActionsFiller
        {
            get
            {
                return this.ActionsFiller;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsFillerItem> __ActionsFiller
        {
            get
            {
                if (this.___ActionsFiller == null)
                {
                    this.___ActionsFiller = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsFillerItem>(
                        this,
                        "ActionsFiller",
                        () => this._ActionsFiller,
                        e => global::System.Object.Equals(e.ActionID, this.ID));
                }
                return this.___ActionsFiller;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsFillerItem> ___ActionsFiller;
        
    }
    #endregion
    
    #region ActionsFillerItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ActionsFillerItem :
        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.IImplementation
    {
        partial void OnActionIDChanged()
        {
            this.___OnPropertyChanged("ActionID");
            this.___OnPropertyChanged("ActionsItem");
        }
        
        partial void OnMAGIDChanged()
        {
            this.___OnPropertyChanged("MAGID");
            this.___OnPropertyChanged("MatsAndGoodsItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        partial void OnPricePerUnitChanged()
        {
            this.___OnPropertyChanged("PricePerUnit");
        }
        
        partial void OnPriceTotalChanged()
        {
            this.___OnPropertyChanged("PriceTotal");
        }
        
        partial void OnQuantity1Changed()
        {
            this.___OnPropertyChanged("Quantity1");
        }
        
        partial void OnQuantity2Changed()
        {
            this.___OnPropertyChanged("Quantity2");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ActionsFillerItem.DetailsClass.IImplementation.ActionsItem
        {
            get
            {
                return this.ActionsItem;
            }
            set
            {
                this.ActionsItem = (global::LightSwitchApplication.Implementation.ActionsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ActionsItem> __ActionsItem
        {
            get
            {
                if (this.___ActionsItem == null)
                {
                    this.___ActionsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ActionsItem>(
                        this,
                        "ActionsItem",
                        new string[] { "ActionID" },
                        e => global::System.Object.Equals(e.ID, this.ActionID),
                        () => this._ActionsItem,
                        e => this._ActionsItem = e);
                }
                return this.___ActionsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ActionsItem> ___ActionsItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ActionsFillerItem.DetailsClass.IImplementation.MatsAndGoodsItem
        {
            get
            {
                return this.MatsAndGoodsItem;
            }
            set
            {
                this.MatsAndGoodsItem = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem
        {
            get
            {
                if (this.___MatsAndGoodsItem == null)
                {
                    this.___MatsAndGoodsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem",
                        new string[] { "MAGID" },
                        e => global::System.Object.Equals(e.ID, this.MAGID),
                        () => this._MatsAndGoodsItem,
                        e => this._MatsAndGoodsItem = e);
                }
                return this.___MatsAndGoodsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem;
        
    }
    #endregion
    
    #region CraftItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CraftItem :
        global::LightSwitchApplication.CraftItem.DetailsClass.IImplementation
    {
        partial void OnRecipeIDChanged()
        {
            this.___OnPropertyChanged("RecipeID");
            this.___OnPropertyChanged("RecipesItem");
        }
        
        partial void OnCraftIDChanged()
        {
            this.___OnPropertyChanged("CraftID");
            this.___OnPropertyChanged("CraftActionItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CraftItem.DetailsClass.IImplementation.RecipesItem
        {
            get
            {
                return this.RecipesItem;
            }
            set
            {
                this.RecipesItem = (global::LightSwitchApplication.Implementation.RecipesItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RecipesItem> __RecipesItem
        {
            get
            {
                if (this.___RecipesItem == null)
                {
                    this.___RecipesItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RecipesItem>(
                        this,
                        "RecipesItem",
                        new string[] { "RecipeID" },
                        e => global::System.Object.Equals(e.ID, this.RecipeID),
                        () => this._RecipesItem,
                        e => this._RecipesItem = e);
                }
                return this.___RecipesItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RecipesItem> ___RecipesItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CraftItem.DetailsClass.IImplementation.CraftActionItem
        {
            get
            {
                return this.CraftActionItem;
            }
            set
            {
                this.CraftActionItem = (global::LightSwitchApplication.Implementation.CraftActionItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CraftActionItem> __CraftActionItem
        {
            get
            {
                if (this.___CraftActionItem == null)
                {
                    this.___CraftActionItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CraftActionItem>(
                        this,
                        "CraftActionItem",
                        new string[] { "CraftID" },
                        e => global::System.Object.Equals(e.ID, this.CraftID),
                        () => this._CraftActionItem,
                        e => this._CraftActionItem = e);
                }
                return this.___CraftActionItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CraftActionItem> ___CraftActionItem;
        
    }
    #endregion
    
    #region CraftActionItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CraftActionItem :
        global::LightSwitchApplication.CraftActionItem.DetailsClass.IImplementation
    {
        partial void OnSkladIDChanged()
        {
            this.___OnPropertyChanged("SkladID");
            this.___OnPropertyChanged("SkladiItem");
        }
        
        partial void OnResponsibleIDChanged()
        {
            this.___OnPropertyChanged("ResponsibleID");
            this.___OnPropertyChanged("ResponsibleItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnNoteChanged()
        {
            this.___OnPropertyChanged("Note");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnDateCreationChanged()
        {
            this.___OnPropertyChanged("DateCreation");
        }
        
        partial void OnDateRealisationChanged()
        {
            this.___OnPropertyChanged("DateRealisation");
        }
        
        partial void OnRealTimeCreationDateChanged()
        {
            this.___OnPropertyChanged("RealTimeCreationDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.CraftActionItem.DetailsClass.IImplementation.Craft
        {
            get
            {
                return this.Craft;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftItem> __Craft
        {
            get
            {
                if (this.___Craft == null)
                {
                    this.___Craft = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftItem>(
                        this,
                        "Craft",
                        () => this._Craft,
                        e => global::System.Object.Equals(e.CraftID, this.ID));
                }
                return this.___Craft;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftItem> ___Craft;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.CraftActionItem.DetailsClass.IImplementation.CraftFiller
        {
            get
            {
                return this.CraftFiller;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftFillerItem> __CraftFiller
        {
            get
            {
                if (this.___CraftFiller == null)
                {
                    this.___CraftFiller = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftFillerItem>(
                        this,
                        "CraftFiller",
                        () => this._CraftFiller,
                        e => global::System.Object.Equals(e.CraftID, this.ID));
                }
                return this.___CraftFiller;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftFillerItem> ___CraftFiller;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CraftActionItem.DetailsClass.IImplementation.SkladiItem
        {
            get
            {
                return this.SkladiItem;
            }
            set
            {
                this.SkladiItem = (global::LightSwitchApplication.Implementation.SkladiItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> __SkladiItem
        {
            get
            {
                if (this.___SkladiItem == null)
                {
                    this.___SkladiItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem>(
                        this,
                        "SkladiItem",
                        new string[] { "SkladID" },
                        e => global::System.Object.Equals(e.ID, this.SkladID),
                        () => this._SkladiItem,
                        e => this._SkladiItem = e);
                }
                return this.___SkladiItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> ___SkladiItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CraftActionItem.DetailsClass.IImplementation.ResponsibleItem
        {
            get
            {
                return this.ResponsibleItem;
            }
            set
            {
                this.ResponsibleItem = (global::LightSwitchApplication.Implementation.ResponsibleItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ResponsibleItem> __ResponsibleItem
        {
            get
            {
                if (this.___ResponsibleItem == null)
                {
                    this.___ResponsibleItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ResponsibleItem>(
                        this,
                        "ResponsibleItem",
                        new string[] { "ResponsibleID" },
                        e => global::System.Object.Equals(e.ID, this.ResponsibleID),
                        () => this._ResponsibleItem,
                        e => this._ResponsibleItem = e);
                }
                return this.___ResponsibleItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ResponsibleItem> ___ResponsibleItem;
        
    }
    #endregion
    
    #region CraftFillerItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CraftFillerItem :
        global::LightSwitchApplication.CraftFillerItem.DetailsClass.IImplementation
    {
        partial void OnMAGIDChanged()
        {
            this.___OnPropertyChanged("MAGID");
            this.___OnPropertyChanged("MatsAndGoodsItem");
        }
        
        partial void OnCraftIDChanged()
        {
            this.___OnPropertyChanged("CraftID");
            this.___OnPropertyChanged("CraftActionItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        partial void OnQuantity1Changed()
        {
            this.___OnPropertyChanged("Quantity1");
        }
        
        partial void OnQuantity2Changed()
        {
            this.___OnPropertyChanged("Quantity2");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CraftFillerItem.DetailsClass.IImplementation.MatsAndGoodsItem
        {
            get
            {
                return this.MatsAndGoodsItem;
            }
            set
            {
                this.MatsAndGoodsItem = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem
        {
            get
            {
                if (this.___MatsAndGoodsItem == null)
                {
                    this.___MatsAndGoodsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem",
                        new string[] { "MAGID" },
                        e => global::System.Object.Equals(e.ID, this.MAGID),
                        () => this._MatsAndGoodsItem,
                        e => this._MatsAndGoodsItem = e);
                }
                return this.___MatsAndGoodsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CraftFillerItem.DetailsClass.IImplementation.CraftActionItem
        {
            get
            {
                return this.CraftActionItem;
            }
            set
            {
                this.CraftActionItem = (global::LightSwitchApplication.Implementation.CraftActionItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CraftActionItem> __CraftActionItem
        {
            get
            {
                if (this.___CraftActionItem == null)
                {
                    this.___CraftActionItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CraftActionItem>(
                        this,
                        "CraftActionItem",
                        new string[] { "CraftID" },
                        e => global::System.Object.Equals(e.ID, this.CraftID),
                        () => this._CraftActionItem,
                        e => this._CraftActionItem = e);
                }
                return this.___CraftActionItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CraftActionItem> ___CraftActionItem;
        
    }
    #endregion
    
    #region LogActionsAndCraftItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class LogActionsAndCraftItem :
        global::LightSwitchApplication.LogActionsAndCraftItem.DetailsClass.IImplementation
    {
        partial void OnMatsAndGoodsItemChanged()
        {
            this.___OnPropertyChanged("MatsAndGoodsItem");
            this.___OnPropertyChanged("MatsAndGoodsItem1");
        }
        
        partial void OnSkladChanged()
        {
            this.___OnPropertyChanged("Sklad");
            this.___OnPropertyChanged("SkladiItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void Onc_DateChanged()
        {
            this.___OnPropertyChanged("c_Date");
        }
        
        partial void OnActionChanged()
        {
            this.___OnPropertyChanged("Action");
        }
        
        partial void OnWayBillNumberChanged()
        {
            this.___OnPropertyChanged("WayBillNumber");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        partial void OnQuantityOnSkladChanged()
        {
            this.___OnPropertyChanged("QuantityOnSklad");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.LogActionsAndCraftItem.DetailsClass.IImplementation.MatsAndGoodsItem1
        {
            get
            {
                return this.MatsAndGoodsItem1;
            }
            set
            {
                this.MatsAndGoodsItem1 = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem1
        {
            get
            {
                if (this.___MatsAndGoodsItem1 == null)
                {
                    this.___MatsAndGoodsItem1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem1",
                        new string[] { "MatsAndGoodsItem" },
                        e => global::System.Object.Equals(e.ID, this.MatsAndGoodsItem),
                        () => this._MatsAndGoodsItem1,
                        e => this._MatsAndGoodsItem1 = e);
                }
                return this.___MatsAndGoodsItem1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem1;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.LogActionsAndCraftItem.DetailsClass.IImplementation.SkladiItem
        {
            get
            {
                return this.SkladiItem;
            }
            set
            {
                this.SkladiItem = (global::LightSwitchApplication.Implementation.SkladiItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> __SkladiItem
        {
            get
            {
                if (this.___SkladiItem == null)
                {
                    this.___SkladiItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem>(
                        this,
                        "SkladiItem",
                        new string[] { "Sklad" },
                        e => global::System.Object.Equals(e.ID, this.Sklad),
                        () => this._SkladiItem,
                        e => this._SkladiItem = e);
                }
                return this.___SkladiItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> ___SkladiItem;
        
    }
    #endregion
    
    #region LogMatsAndGoodsQuantitiesItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class LogMatsAndGoodsQuantitiesItem :
        global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.IImplementation
    {
        partial void OnMatsAndGoodsItemIDChanged()
        {
            this.___OnPropertyChanged("MatsAndGoodsItemID");
            this.___OnPropertyChanged("MatsAndGoodsItem");
        }
        
        partial void OnSkladItemIDChanged()
        {
            this.___OnPropertyChanged("SkladItemID");
            this.___OnPropertyChanged("SkladiItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void Onc_DateChanged()
        {
            this.___OnPropertyChanged("c_Date");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.IImplementation.MatsAndGoodsItem
        {
            get
            {
                return this.MatsAndGoodsItem;
            }
            set
            {
                this.MatsAndGoodsItem = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem
        {
            get
            {
                if (this.___MatsAndGoodsItem == null)
                {
                    this.___MatsAndGoodsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem",
                        new string[] { "MatsAndGoodsItemID" },
                        e => global::System.Object.Equals(e.ID, this.MatsAndGoodsItemID),
                        () => this._MatsAndGoodsItem,
                        e => this._MatsAndGoodsItem = e);
                }
                return this.___MatsAndGoodsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem.DetailsClass.IImplementation.SkladiItem
        {
            get
            {
                return this.SkladiItem;
            }
            set
            {
                this.SkladiItem = (global::LightSwitchApplication.Implementation.SkladiItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> __SkladiItem
        {
            get
            {
                if (this.___SkladiItem == null)
                {
                    this.___SkladiItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem>(
                        this,
                        "SkladiItem",
                        new string[] { "SkladItemID" },
                        e => global::System.Object.Equals(e.ID, this.SkladItemID),
                        () => this._SkladiItem,
                        e => this._SkladiItem = e);
                }
                return this.___SkladiItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> ___SkladiItem;
        
    }
    #endregion
    
    #region MatsAndGoodsItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class MatsAndGoodsItem :
        global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation
    {
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnCategoryChanged()
        {
            this.___OnPropertyChanged("Category");
        }
        
        partial void OnUnitChanged()
        {
            this.___OnPropertyChanged("Unit");
        }
        
        partial void OnNoteChanged()
        {
            this.___OnPropertyChanged("Note");
        }
        
        partial void OnFullNameChanged()
        {
            this.___OnPropertyChanged("FullName");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnTotalQuantityChanged()
        {
            this.___OnPropertyChanged("TotalQuantity");
        }
        
        partial void OnTotalQuantityNeededChanged()
        {
            this.___OnPropertyChanged("TotalQuantityNeeded");
        }
        
        partial void OnTotalQuantityDifferenceChanged()
        {
            this.___OnPropertyChanged("TotalQuantityDifference");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.MatsAndGoodsQuantities
        {
            get
            {
                return this.MatsAndGoodsQuantities;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem> __MatsAndGoodsQuantities
        {
            get
            {
                if (this.___MatsAndGoodsQuantities == null)
                {
                    this.___MatsAndGoodsQuantities = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem>(
                        this,
                        "MatsAndGoodsQuantities",
                        () => this._MatsAndGoodsQuantities,
                        e => global::System.Object.Equals(e.MatsAndGoodID, this.ID));
                }
                return this.___MatsAndGoodsQuantities;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem> ___MatsAndGoodsQuantities;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.Recipes
        {
            get
            {
                return this.Recipes;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesItem> __Recipes
        {
            get
            {
                if (this.___Recipes == null)
                {
                    this.___Recipes = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesItem>(
                        this,
                        "Recipes",
                        () => this._Recipes,
                        e => global::System.Object.Equals(e.DoneID, this.ID));
                }
                return this.___Recipes;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesItem> ___Recipes;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.RecipesComponents
        {
            get
            {
                return this.RecipesComponents;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesComponentsItem> __RecipesComponents
        {
            get
            {
                if (this.___RecipesComponents == null)
                {
                    this.___RecipesComponents = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesComponentsItem>(
                        this,
                        "RecipesComponents",
                        () => this._RecipesComponents,
                        e => global::System.Object.Equals(e.ComponentID, this.ID));
                }
                return this.___RecipesComponents;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesComponentsItem> ___RecipesComponents;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.ActionsFiller
        {
            get
            {
                return this.ActionsFiller;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsFillerItem> __ActionsFiller
        {
            get
            {
                if (this.___ActionsFiller == null)
                {
                    this.___ActionsFiller = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsFillerItem>(
                        this,
                        "ActionsFiller",
                        () => this._ActionsFiller,
                        e => global::System.Object.Equals(e.MAGID, this.ID));
                }
                return this.___ActionsFiller;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsFillerItem> ___ActionsFiller;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.CraftFiller
        {
            get
            {
                return this.CraftFiller;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftFillerItem> __CraftFiller
        {
            get
            {
                if (this.___CraftFiller == null)
                {
                    this.___CraftFiller = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftFillerItem>(
                        this,
                        "CraftFiller",
                        () => this._CraftFiller,
                        e => global::System.Object.Equals(e.MAGID, this.ID));
                }
                return this.___CraftFiller;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftFillerItem> ___CraftFiller;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.LogActionsAndCraft
        {
            get
            {
                return this.LogActionsAndCraft;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogActionsAndCraftItem> __LogActionsAndCraft
        {
            get
            {
                if (this.___LogActionsAndCraft == null)
                {
                    this.___LogActionsAndCraft = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogActionsAndCraftItem>(
                        this,
                        "LogActionsAndCraft",
                        () => this._LogActionsAndCraft,
                        e => global::System.Object.Equals(e.MatsAndGoodsItem, this.ID));
                }
                return this.___LogActionsAndCraft;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogActionsAndCraftItem> ___LogActionsAndCraft;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.LogMatsAndGoodsQuantities
        {
            get
            {
                return this.LogMatsAndGoodsQuantities;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem> __LogMatsAndGoodsQuantities
        {
            get
            {
                if (this.___LogMatsAndGoodsQuantities == null)
                {
                    this.___LogMatsAndGoodsQuantities = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem>(
                        this,
                        "LogMatsAndGoodsQuantities",
                        () => this._LogMatsAndGoodsQuantities,
                        e => global::System.Object.Equals(e.MatsAndGoodsItemID, this.ID));
                }
                return this.___LogMatsAndGoodsQuantities;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem> ___LogMatsAndGoodsQuantities;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass.IImplementation.MatsAndGoodsPrices
        {
            get
            {
                return this.MatsAndGoodsPrices;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem> __MatsAndGoodsPrices
        {
            get
            {
                if (this.___MatsAndGoodsPrices == null)
                {
                    this.___MatsAndGoodsPrices = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem>(
                        this,
                        "MatsAndGoodsPrices",
                        () => this._MatsAndGoodsPrices,
                        e => global::System.Object.Equals(e.MAGID, this.ID));
                }
                return this.___MatsAndGoodsPrices;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem> ___MatsAndGoodsPrices;
        
    }
    #endregion
    
    #region MatsAndGoodsPricesItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class MatsAndGoodsPricesItem :
        global::LightSwitchApplication.MatsAndGoodsPricesItem.DetailsClass.IImplementation
    {
        partial void OnMAGIDChanged()
        {
            this.___OnPropertyChanged("MAGID");
            this.___OnPropertyChanged("MatsAndGoodsItem");
        }
        
        partial void OnSupplierIDChanged()
        {
            this.___OnPropertyChanged("SupplierID");
            this.___OnPropertyChanged("SuppliersItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnLastPriceChanged()
        {
            this.___OnPropertyChanged("LastPrice");
        }
        
        partial void OnLastDateChanged()
        {
            this.___OnPropertyChanged("LastDate");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.MatsAndGoodsPricesItem.DetailsClass.IImplementation.MatsAndGoodsItem
        {
            get
            {
                return this.MatsAndGoodsItem;
            }
            set
            {
                this.MatsAndGoodsItem = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem
        {
            get
            {
                if (this.___MatsAndGoodsItem == null)
                {
                    this.___MatsAndGoodsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem",
                        new string[] { "MAGID" },
                        e => global::System.Object.Equals(e.ID, this.MAGID),
                        () => this._MatsAndGoodsItem,
                        e => this._MatsAndGoodsItem = e);
                }
                return this.___MatsAndGoodsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.MatsAndGoodsPricesItem.DetailsClass.IImplementation.SuppliersItem
        {
            get
            {
                return this.SuppliersItem;
            }
            set
            {
                this.SuppliersItem = (global::LightSwitchApplication.Implementation.SuppliersItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SuppliersItem> __SuppliersItem
        {
            get
            {
                if (this.___SuppliersItem == null)
                {
                    this.___SuppliersItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SuppliersItem>(
                        this,
                        "SuppliersItem",
                        new string[] { "SupplierID" },
                        e => global::System.Object.Equals(e.ID, this.SupplierID),
                        () => this._SuppliersItem,
                        e => this._SuppliersItem = e);
                }
                return this.___SuppliersItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SuppliersItem> ___SuppliersItem;
        
    }
    #endregion
    
    #region MatsAndGoodsQuantitiesItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class MatsAndGoodsQuantitiesItem :
        global::LightSwitchApplication.MatsAndGoodsQuantitiesItem.DetailsClass.IImplementation
    {
        partial void OnMatsAndGoodIDChanged()
        {
            this.___OnPropertyChanged("MatsAndGoodID");
            this.___OnPropertyChanged("MatsAndGoodsItem");
        }
        
        partial void OnSkladIDChanged()
        {
            this.___OnPropertyChanged("SkladID");
            this.___OnPropertyChanged("SkladiItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.MatsAndGoodsQuantitiesItem.DetailsClass.IImplementation.MatsAndGoodsItem
        {
            get
            {
                return this.MatsAndGoodsItem;
            }
            set
            {
                this.MatsAndGoodsItem = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem
        {
            get
            {
                if (this.___MatsAndGoodsItem == null)
                {
                    this.___MatsAndGoodsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem",
                        new string[] { "MatsAndGoodID" },
                        e => global::System.Object.Equals(e.ID, this.MatsAndGoodID),
                        () => this._MatsAndGoodsItem,
                        e => this._MatsAndGoodsItem = e);
                }
                return this.___MatsAndGoodsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.MatsAndGoodsQuantitiesItem.DetailsClass.IImplementation.SkladiItem
        {
            get
            {
                return this.SkladiItem;
            }
            set
            {
                this.SkladiItem = (global::LightSwitchApplication.Implementation.SkladiItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> __SkladiItem
        {
            get
            {
                if (this.___SkladiItem == null)
                {
                    this.___SkladiItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem>(
                        this,
                        "SkladiItem",
                        new string[] { "SkladID" },
                        e => global::System.Object.Equals(e.ID, this.SkladID),
                        () => this._SkladiItem,
                        e => this._SkladiItem = e);
                }
                return this.___SkladiItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> ___SkladiItem;
        
    }
    #endregion
    
    #region RecipesItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RecipesItem :
        global::LightSwitchApplication.RecipesItem.DetailsClass.IImplementation
    {
        partial void OnDoneIDChanged()
        {
            this.___OnPropertyChanged("DoneID");
            this.___OnPropertyChanged("MatsAndGoodsItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnQuantityDoneChanged()
        {
            this.___OnPropertyChanged("QuantityDone");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RecipesItem.DetailsClass.IImplementation.MatsAndGoodsItem
        {
            get
            {
                return this.MatsAndGoodsItem;
            }
            set
            {
                this.MatsAndGoodsItem = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem
        {
            get
            {
                if (this.___MatsAndGoodsItem == null)
                {
                    this.___MatsAndGoodsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem",
                        new string[] { "DoneID" },
                        e => global::System.Object.Equals(e.ID, this.DoneID),
                        () => this._MatsAndGoodsItem,
                        e => this._MatsAndGoodsItem = e);
                }
                return this.___MatsAndGoodsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RecipesItem.DetailsClass.IImplementation.RecipesComponents
        {
            get
            {
                return this.RecipesComponents;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesComponentsItem> __RecipesComponents
        {
            get
            {
                if (this.___RecipesComponents == null)
                {
                    this.___RecipesComponents = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesComponentsItem>(
                        this,
                        "RecipesComponents",
                        () => this._RecipesComponents,
                        e => global::System.Object.Equals(e.RecipeID, this.ID));
                }
                return this.___RecipesComponents;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.RecipesComponentsItem> ___RecipesComponents;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RecipesItem.DetailsClass.IImplementation.Craft
        {
            get
            {
                return this.Craft;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftItem> __Craft
        {
            get
            {
                if (this.___Craft == null)
                {
                    this.___Craft = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftItem>(
                        this,
                        "Craft",
                        () => this._Craft,
                        e => global::System.Object.Equals(e.RecipeID, this.ID));
                }
                return this.___Craft;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftItem> ___Craft;
        
    }
    #endregion
    
    #region RecipesComponentsItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RecipesComponentsItem :
        global::LightSwitchApplication.RecipesComponentsItem.DetailsClass.IImplementation
    {
        partial void OnComponentIDChanged()
        {
            this.___OnPropertyChanged("ComponentID");
            this.___OnPropertyChanged("MatsAndGoodsItem");
        }
        
        partial void OnRecipeIDChanged()
        {
            this.___OnPropertyChanged("RecipeID");
            this.___OnPropertyChanged("RecipesItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RecipesComponentsItem.DetailsClass.IImplementation.MatsAndGoodsItem
        {
            get
            {
                return this.MatsAndGoodsItem;
            }
            set
            {
                this.MatsAndGoodsItem = (global::LightSwitchApplication.Implementation.MatsAndGoodsItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> __MatsAndGoodsItem
        {
            get
            {
                if (this.___MatsAndGoodsItem == null)
                {
                    this.___MatsAndGoodsItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem>(
                        this,
                        "MatsAndGoodsItem",
                        new string[] { "ComponentID" },
                        e => global::System.Object.Equals(e.ID, this.ComponentID),
                        () => this._MatsAndGoodsItem,
                        e => this._MatsAndGoodsItem = e);
                }
                return this.___MatsAndGoodsItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.MatsAndGoodsItem> ___MatsAndGoodsItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RecipesComponentsItem.DetailsClass.IImplementation.RecipesItem
        {
            get
            {
                return this.RecipesItem;
            }
            set
            {
                this.RecipesItem = (global::LightSwitchApplication.Implementation.RecipesItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RecipesItem> __RecipesItem
        {
            get
            {
                if (this.___RecipesItem == null)
                {
                    this.___RecipesItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RecipesItem>(
                        this,
                        "RecipesItem",
                        new string[] { "RecipeID" },
                        e => global::System.Object.Equals(e.ID, this.RecipeID),
                        () => this._RecipesItem,
                        e => this._RecipesItem = e);
                }
                return this.___RecipesItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.RecipesItem> ___RecipesItem;
        
    }
    #endregion
    
    #region ResponsibleItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ResponsibleItem :
        global::LightSwitchApplication.ResponsibleItem.DetailsClass.IImplementation
    {
        partial void OnSkladIDChanged()
        {
            this.___OnPropertyChanged("SkladID");
            this.___OnPropertyChanged("SkladiItem");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnNoteChanged()
        {
            this.___OnPropertyChanged("Note");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ResponsibleItem.DetailsClass.IImplementation.CraftAction
        {
            get
            {
                return this.CraftAction;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftActionItem> __CraftAction
        {
            get
            {
                if (this.___CraftAction == null)
                {
                    this.___CraftAction = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftActionItem>(
                        this,
                        "CraftAction",
                        () => this._CraftAction,
                        e => global::System.Object.Equals(e.ResponsibleID, this.ID));
                }
                return this.___CraftAction;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftActionItem> ___CraftAction;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ResponsibleItem.DetailsClass.IImplementation.SkladiItem
        {
            get
            {
                return this.SkladiItem;
            }
            set
            {
                this.SkladiItem = (global::LightSwitchApplication.Implementation.SkladiItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> __SkladiItem
        {
            get
            {
                if (this.___SkladiItem == null)
                {
                    this.___SkladiItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem>(
                        this,
                        "SkladiItem",
                        new string[] { "SkladID" },
                        e => global::System.Object.Equals(e.ID, this.SkladID),
                        () => this._SkladiItem,
                        e => this._SkladiItem = e);
                }
                return this.___SkladiItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.SkladiItem> ___SkladiItem;
        
    }
    #endregion
    
    #region SkladiItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SkladiItem :
        global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation
    {
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnAdressChanged()
        {
            this.___OnPropertyChanged("Adress");
        }
        
        partial void OnNoteChanged()
        {
            this.___OnPropertyChanged("Note");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation.Actions
        {
            get
            {
                return this.Actions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem> __Actions
        {
            get
            {
                if (this.___Actions == null)
                {
                    this.___Actions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem>(
                        this,
                        "Actions",
                        () => this._Actions,
                        e => global::System.Object.Equals(e.FromSkladID, this.ID));
                }
                return this.___Actions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem> ___Actions;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation.Actions1
        {
            get
            {
                return this.Actions1;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem> __Actions1
        {
            get
            {
                if (this.___Actions1 == null)
                {
                    this.___Actions1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem>(
                        this,
                        "Actions1",
                        () => this._Actions1,
                        e => global::System.Object.Equals(e.ToSkladID, this.ID));
                }
                return this.___Actions1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem> ___Actions1;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation.MatsAndGoodsQuantities
        {
            get
            {
                return this.MatsAndGoodsQuantities;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem> __MatsAndGoodsQuantities
        {
            get
            {
                if (this.___MatsAndGoodsQuantities == null)
                {
                    this.___MatsAndGoodsQuantities = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem>(
                        this,
                        "MatsAndGoodsQuantities",
                        () => this._MatsAndGoodsQuantities,
                        e => global::System.Object.Equals(e.SkladID, this.ID));
                }
                return this.___MatsAndGoodsQuantities;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem> ___MatsAndGoodsQuantities;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation.CraftAction
        {
            get
            {
                return this.CraftAction;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftActionItem> __CraftAction
        {
            get
            {
                if (this.___CraftAction == null)
                {
                    this.___CraftAction = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftActionItem>(
                        this,
                        "CraftAction",
                        () => this._CraftAction,
                        e => global::System.Object.Equals(e.SkladID, this.ID));
                }
                return this.___CraftAction;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CraftActionItem> ___CraftAction;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation.Responsible
        {
            get
            {
                return this.Responsible;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ResponsibleItem> __Responsible
        {
            get
            {
                if (this.___Responsible == null)
                {
                    this.___Responsible = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ResponsibleItem>(
                        this,
                        "Responsible",
                        () => this._Responsible,
                        e => global::System.Object.Equals(e.SkladID, this.ID));
                }
                return this.___Responsible;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ResponsibleItem> ___Responsible;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation.LogMatsAndGoodsQuantities
        {
            get
            {
                return this.LogMatsAndGoodsQuantities;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem> __LogMatsAndGoodsQuantities
        {
            get
            {
                if (this.___LogMatsAndGoodsQuantities == null)
                {
                    this.___LogMatsAndGoodsQuantities = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem>(
                        this,
                        "LogMatsAndGoodsQuantities",
                        () => this._LogMatsAndGoodsQuantities,
                        e => global::System.Object.Equals(e.SkladItemID, this.ID));
                }
                return this.___LogMatsAndGoodsQuantities;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem> ___LogMatsAndGoodsQuantities;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SkladiItem.DetailsClass.IImplementation.LogActionsAndCraft
        {
            get
            {
                return this.LogActionsAndCraft;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogActionsAndCraftItem> __LogActionsAndCraft
        {
            get
            {
                if (this.___LogActionsAndCraft == null)
                {
                    this.___LogActionsAndCraft = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogActionsAndCraftItem>(
                        this,
                        "LogActionsAndCraft",
                        () => this._LogActionsAndCraft,
                        e => global::System.Object.Equals(e.Sklad, this.ID));
                }
                return this.___LogActionsAndCraft;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.LogActionsAndCraftItem> ___LogActionsAndCraft;
        
    }
    #endregion
    
    #region SuppliersItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/skladData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SuppliersItem :
        global::LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation
    {
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnFullNameChanged()
        {
            this.___OnPropertyChanged("FullName");
        }
        
        partial void OnCountryChanged()
        {
            this.___OnPropertyChanged("Country");
        }
        
        partial void OnRegionChanged()
        {
            this.___OnPropertyChanged("Region");
        }
        
        partial void OnCityChanged()
        {
            this.___OnPropertyChanged("City");
        }
        
        partial void OnAdressChanged()
        {
            this.___OnPropertyChanged("Adress");
        }
        
        partial void OnPostcodeChanged()
        {
            this.___OnPropertyChanged("Postcode");
        }
        
        partial void OnINN_KPPChanged()
        {
            this.___OnPropertyChanged("INN_KPP");
        }
        
        partial void OnOGRNChanged()
        {
            this.___OnPropertyChanged("OGRN");
        }
        
        partial void OnOKPOChanged()
        {
            this.___OnPropertyChanged("OKPO");
        }
        
        partial void OnOKVEDChanged()
        {
            this.___OnPropertyChanged("OKVED");
        }
        
        partial void OnContactNameChanged()
        {
            this.___OnPropertyChanged("ContactName");
        }
        
        partial void OnPhoneNumberChanged()
        {
            this.___OnPropertyChanged("PhoneNumber");
        }
        
        partial void OnFaxNumberChanged()
        {
            this.___OnPropertyChanged("FaxNumber");
        }
        
        partial void OnNoteChanged()
        {
            this.___OnPropertyChanged("Note");
        }
        
        partial void OnNDSChanged()
        {
            this.___OnPropertyChanged("NDS");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.Actions
        {
            get
            {
                return this.Actions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem> __Actions
        {
            get
            {
                if (this.___Actions == null)
                {
                    this.___Actions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem>(
                        this,
                        "Actions",
                        () => this._Actions,
                        e => global::System.Object.Equals(e.SupplierID, this.ID));
                }
                return this.___Actions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ActionsItem> ___Actions;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.MatsAndGoodsPrices
        {
            get
            {
                return this.MatsAndGoodsPrices;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem> __MatsAndGoodsPrices
        {
            get
            {
                if (this.___MatsAndGoodsPrices == null)
                {
                    this.___MatsAndGoodsPrices = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem>(
                        this,
                        "MatsAndGoodsPrices",
                        () => this._MatsAndGoodsPrices,
                        e => global::System.Object.Equals(e.SupplierID, this.ID));
                }
                return this.___MatsAndGoodsPrices;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem> ___MatsAndGoodsPrices;
        
    }
    #endregion
    
    #region Table1Item
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Table1Item :
        global::LightSwitchApplication.Table1Item.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
    }
    #endregion
    
    #region skladData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class skladData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.ActionsItem))
            {
                return new global::LightSwitchApplication.Implementation.ActionsItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ActionsFillerItem))
            {
                return new global::LightSwitchApplication.Implementation.ActionsFillerItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CraftItem))
            {
                return new global::LightSwitchApplication.Implementation.CraftItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CraftActionItem))
            {
                return new global::LightSwitchApplication.Implementation.CraftActionItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CraftFillerItem))
            {
                return new global::LightSwitchApplication.Implementation.CraftFillerItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.LogActionsAndCraftItem))
            {
                return new global::LightSwitchApplication.Implementation.LogActionsAndCraftItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem))
            {
                return new global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.MatsAndGoodsItem))
            {
                return new global::LightSwitchApplication.Implementation.MatsAndGoodsItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.MatsAndGoodsPricesItem))
            {
                return new global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.MatsAndGoodsQuantitiesItem))
            {
                return new global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RecipesItem))
            {
                return new global::LightSwitchApplication.Implementation.RecipesItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RecipesComponentsItem))
            {
                return new global::LightSwitchApplication.Implementation.RecipesComponentsItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ResponsibleItem))
            {
                return new global::LightSwitchApplication.Implementation.ResponsibleItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SkladiItem))
            {
                return new global::LightSwitchApplication.Implementation.SkladiItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SuppliersItem))
            {
                return new global::LightSwitchApplication.Implementation.SuppliersItem();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.skladData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Table1Item))
            {
                return new global::LightSwitchApplication.Implementation.Table1Item();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.skladData))
            {
                return new global::LightSwitchApplication.skladData();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.skladData))
            {
                return new global::LightSwitchApplication.Implementation.skladData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../skladData.svc"));
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.ActionsItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ActionsItem);
            }
            if (typeof(global::LightSwitchApplication.ActionsFillerItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ActionsFillerItem);
            }
            if (typeof(global::LightSwitchApplication.CraftItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CraftItem);
            }
            if (typeof(global::LightSwitchApplication.CraftActionItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CraftActionItem);
            }
            if (typeof(global::LightSwitchApplication.CraftFillerItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CraftFillerItem);
            }
            if (typeof(global::LightSwitchApplication.LogActionsAndCraftItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.LogActionsAndCraftItem);
            }
            if (typeof(global::LightSwitchApplication.LogMatsAndGoodsQuantitiesItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.LogMatsAndGoodsQuantitiesItem);
            }
            if (typeof(global::LightSwitchApplication.MatsAndGoodsItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.MatsAndGoodsItem);
            }
            if (typeof(global::LightSwitchApplication.MatsAndGoodsPricesItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.MatsAndGoodsPricesItem);
            }
            if (typeof(global::LightSwitchApplication.MatsAndGoodsQuantitiesItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.MatsAndGoodsQuantitiesItem);
            }
            if (typeof(global::LightSwitchApplication.RecipesItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RecipesItem);
            }
            if (typeof(global::LightSwitchApplication.RecipesComponentsItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RecipesComponentsItem);
            }
            if (typeof(global::LightSwitchApplication.ResponsibleItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ResponsibleItem);
            }
            if (typeof(global::LightSwitchApplication.SkladiItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SkladiItem);
            }
            if (typeof(global::LightSwitchApplication.SuppliersItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SuppliersItem);
            }
            if (typeof(global::LightSwitchApplication.Table1Item) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Table1Item);
            }
            return null;
        }
    }
}
