

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Отсутствует описание модели
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class CraftItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Инициализирует новый экземпляр сущности CraftItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CraftItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CraftItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CraftItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CraftItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Получает объект Application для данного приложения.  Объект Application предоставляет доступ к активным экранам, методы для открытых экранов и доступ к текущему пользователю.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Получает вмещающую рабочую область данных.  Рабочая область данных предоставляет доступ ко всем источникам данных в приложении.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ID
        {
            get
            {
                return global::LightSwitchApplication.CraftItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Quantity
        {
            get
            {
                return global::LightSwitchApplication.CraftItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.Quantity);
            }
            set
            {
                global::LightSwitchApplication.CraftItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.Quantity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.RecipesItem RecipesItem
        {
            get
            {
                return global::LightSwitchApplication.CraftItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.RecipesItem);
            }
            set
            {
                global::LightSwitchApplication.CraftItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.RecipesItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RecipesItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RecipesItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RecipesItem_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.CraftActionItem CraftActionItem
        {
            get
            {
                return global::LightSwitchApplication.CraftItem.DetailsClass.GetValue(this, global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.CraftActionItem);
            }
            set
            {
                global::LightSwitchApplication.CraftItem.DetailsClass.SetValue(this, global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.CraftActionItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftActionItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftActionItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CraftActionItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CraftItem,
                global::LightSwitchApplication.CraftItem.DetailsClass,
                global::LightSwitchApplication.CraftItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.CraftItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass>.Entry
                __CraftItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.CraftItem.DetailsClass.__CraftItem_CreateNew,
                    global::LightSwitchApplication.CraftItem.DetailsClass.__CraftItem_Created,
                    global::LightSwitchApplication.CraftItem.DetailsClass.__CraftItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CraftItem __CraftItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CraftItem> es)
            {
                return new global::LightSwitchApplication.CraftItem(es);
            }
            private static void __CraftItem_Created(global::LightSwitchApplication.CraftItem e)
            {
                e.CraftItem_Created();
            }
            private static bool __CraftItem_AllowSaveWithErrors(global::LightSwitchApplication.CraftItem e)
            {
                bool result = false;
                e.CraftItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CraftItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, decimal> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::System.Nullable<decimal>> Quantity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.Quantity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.RecipesItem> RecipesItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.RecipesItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.RecipesItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.CraftActionItem> CraftActionItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.CraftActionItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new decimal ID { get; }
                new global::System.Nullable<decimal> Quantity { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation RecipesItem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation CraftActionItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, decimal>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, decimal>.Entry(
                        "ID",
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.CraftItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.CraftItem e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.CraftItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static decimal _ID_GetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.CraftItem e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Quantity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Quantity",
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._Quantity_Stub,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._Quantity_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._Quantity_Validate,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._Quantity_GetImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._Quantity_SetImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._Quantity_OnValueChanged);
                private static void _Quantity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.CraftItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity, sf);
                }
                private static bool _Quantity_ComputeIsReadOnly(global::LightSwitchApplication.CraftItem e)
                {
                    bool result = false;
                    e.Quantity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity_Validate(global::LightSwitchApplication.CraftItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity_Validate(r);
                }
                private static global::System.Nullable<decimal> _Quantity_GetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity;
                }
                private static void _Quantity_SetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Quantity = v;
                }
                private static void _Quantity_OnValueChanged(global::LightSwitchApplication.CraftItem e)
                {
                    e.Quantity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.RecipesItem>.Entry
                    RecipesItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.RecipesItem>.Entry(
                        "RecipesItem",
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_Stub,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_Validate,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_GetImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_SetImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_Refresh,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._RecipesItem_OnValueChanged);
                private static void _RecipesItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.RecipesItem>.Data> c, global::LightSwitchApplication.CraftItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RecipesItem, sf);
                }
                private static bool _RecipesItem_ComputeIsReadOnly(global::LightSwitchApplication.CraftItem e)
                {
                    bool result = false;
                    e.RecipesItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _RecipesItem_Validate(global::LightSwitchApplication.CraftItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RecipesItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _RecipesItem_GetCoreImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RecipesItem;
                }
                private static global::LightSwitchApplication.RecipesItem _RecipesItem_GetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.RecipesItem, global::LightSwitchApplication.RecipesItem.DetailsClass>(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.RecipesItem, ref d._RecipesItem);
                }
                private static void _RecipesItem_SetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d, global::LightSwitchApplication.RecipesItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.RecipesItem, ref d._RecipesItem, (i, ev) => i.RecipesItem = ev, v);
                }
                private static void _RecipesItem_Refresh(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.RecipesItem, ref d._RecipesItem);
                }
                private static void _RecipesItem_OnValueChanged(global::LightSwitchApplication.CraftItem e)
                {
                    e.RecipesItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Entry
                    CraftActionItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Entry(
                        "CraftActionItem",
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_Stub,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_Validate,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_GetImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_SetImplementationValue,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_Refresh,
                        global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties._CraftActionItem_OnValueChanged);
                private static void _CraftActionItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CraftItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Data> c, global::LightSwitchApplication.CraftItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CraftActionItem, sf);
                }
                private static bool _CraftActionItem_ComputeIsReadOnly(global::LightSwitchApplication.CraftItem e)
                {
                    bool result = false;
                    e.CraftActionItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _CraftActionItem_Validate(global::LightSwitchApplication.CraftItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CraftActionItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _CraftActionItem_GetCoreImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CraftActionItem;
                }
                private static global::LightSwitchApplication.CraftActionItem _CraftActionItem_GetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.CraftActionItem, global::LightSwitchApplication.CraftActionItem.DetailsClass>(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.CraftActionItem, ref d._CraftActionItem);
                }
                private static void _CraftActionItem_SetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass d, global::LightSwitchApplication.CraftActionItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.CraftActionItem, ref d._CraftActionItem, (i, ev) => i.CraftActionItem = ev, v);
                }
                private static void _CraftActionItem_Refresh(global::LightSwitchApplication.CraftItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CraftItem.DetailsClass.PropertySetProperties.CraftActionItem, ref d._CraftActionItem);
                }
                private static void _CraftActionItem_OnValueChanged(global::LightSwitchApplication.CraftItem e)
                {
                    e.CraftActionItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, decimal>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::System.Nullable<decimal>>.Data _Quantity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.RecipesItem>.Data _RecipesItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CraftItem, global::LightSwitchApplication.CraftItem.DetailsClass, global::LightSwitchApplication.CraftActionItem>.Data _CraftActionItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
