

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Отсутствует описание модели
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class ActionsFillerItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Инициализирует новый экземпляр сущности ActionsFillerItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ActionsFillerItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ActionsFillerItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ActionsFillerItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ActionsFillerItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionsFillerItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionsFillerItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Получает объект Application для данного приложения.  Объект Application предоставляет доступ к активным экранам, методы для открытых экранов и доступ к текущему пользователю.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Получает вмещающую рабочую область данных.  Рабочая область данных предоставляет доступ ко всем источникам данных в приложении.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ID
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Quantity
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity);
            }
            set
            {
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> PricePerUnit
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.PricePerUnit);
            }
            set
            {
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.PricePerUnit, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PricePerUnit_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PricePerUnit_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PricePerUnit_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> PriceTotal
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.PriceTotal);
            }
            set
            {
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.PriceTotal, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PriceTotal_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PriceTotal_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PriceTotal_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Quantity1
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity1);
            }
            set
            {
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity1_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Quantity2
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity2);
            }
            set
            {
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity2, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity2_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity2_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity2_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MAGed
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MAGed);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MAGed_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MAGed_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ActionsItem ActionsItem
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ActionsItem);
            }
            set
            {
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ActionsItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionsItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionsItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionsItem_Changed();

        /// <summary>
        /// Отсутствует описание модели
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.MatsAndGoodsItem MatsAndGoodsItem
        {
            get
            {
                return global::LightSwitchApplication.ActionsFillerItem.DetailsClass.GetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem);
            }
            set
            {
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.SetValue(this, global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MatsAndGoodsItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ActionsFillerItem,
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass,
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass>.Entry
                __ActionsFillerItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.ActionsFillerItem.DetailsClass.__ActionsFillerItem_CreateNew,
                    global::LightSwitchApplication.ActionsFillerItem.DetailsClass.__ActionsFillerItem_Created,
                    global::LightSwitchApplication.ActionsFillerItem.DetailsClass.__ActionsFillerItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ActionsFillerItem __ActionsFillerItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ActionsFillerItem> es)
            {
                return new global::LightSwitchApplication.ActionsFillerItem(es);
            }
            private static void __ActionsFillerItem_Created(global::LightSwitchApplication.ActionsFillerItem e)
            {
                e.ActionsFillerItem_Created();
            }
            private static bool __ActionsFillerItem_AllowSaveWithErrors(global::LightSwitchApplication.ActionsFillerItem e)
            {
                bool result = false;
                e.ActionsFillerItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal> Quantity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>> PricePerUnit
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.PricePerUnit) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>> PriceTotal
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.PriceTotal) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>> Quantity1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>> Quantity2
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.Quantity2) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, string> MAGed
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MAGed) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.ActionsItem> ActionsItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ActionsItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.ActionsItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem> MatsAndGoodsItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new decimal ID { get; }
                new decimal Quantity { get; set; }
                new global::System.Nullable<decimal> PricePerUnit { get; set; }
                new global::System.Nullable<decimal> PriceTotal { get; set; }
                new global::System.Nullable<decimal> Quantity1 { get; set; }
                new global::System.Nullable<decimal> Quantity2 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ActionsItem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation MatsAndGoodsItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Entry(
                        "ID",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static decimal _ID_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Entry
                    Quantity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Entry(
                        "Quantity",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity_GetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity_SetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity_OnValueChanged);
                private static void _Quantity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity, sf);
                }
                private static bool _Quantity_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.Quantity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity_Validate(r);
                }
                private static decimal _Quantity_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity;
                }
                private static void _Quantity_SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Quantity = v;
                }
                private static void _Quantity_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.Quantity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    PricePerUnit = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "PricePerUnit",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PricePerUnit_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PricePerUnit_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PricePerUnit_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PricePerUnit_GetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PricePerUnit_SetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PricePerUnit_OnValueChanged);
                private static void _PricePerUnit_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PricePerUnit, sf);
                }
                private static bool _PricePerUnit_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.PricePerUnit_IsReadOnly(ref result);
                    return result;
                }
                private static void _PricePerUnit_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PricePerUnit_Validate(r);
                }
                private static global::System.Nullable<decimal> _PricePerUnit_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PricePerUnit;
                }
                private static void _PricePerUnit_SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.PricePerUnit = v;
                }
                private static void _PricePerUnit_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.PricePerUnit_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    PriceTotal = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "PriceTotal",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PriceTotal_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PriceTotal_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PriceTotal_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PriceTotal_GetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PriceTotal_SetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._PriceTotal_OnValueChanged);
                private static void _PriceTotal_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PriceTotal, sf);
                }
                private static bool _PriceTotal_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.PriceTotal_IsReadOnly(ref result);
                    return result;
                }
                private static void _PriceTotal_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PriceTotal_Validate(r);
                }
                private static global::System.Nullable<decimal> _PriceTotal_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PriceTotal;
                }
                private static void _PriceTotal_SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.PriceTotal = v;
                }
                private static void _PriceTotal_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.PriceTotal_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Quantity1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Quantity1",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity1_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity1_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity1_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity1_GetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity1_SetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity1_OnValueChanged);
                private static void _Quantity1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity1, sf);
                }
                private static bool _Quantity1_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.Quantity1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity1_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity1_Validate(r);
                }
                private static global::System.Nullable<decimal> _Quantity1_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity1;
                }
                private static void _Quantity1_SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Quantity1 = v;
                }
                private static void _Quantity1_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.Quantity1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Quantity2 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Quantity2",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity2_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity2_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity2_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity2_GetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity2_SetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._Quantity2_OnValueChanged);
                private static void _Quantity2_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity2, sf);
                }
                private static bool _Quantity2_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.Quantity2_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity2_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity2_Validate(r);
                }
                private static global::System.Nullable<decimal> _Quantity2_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity2;
                }
                private static void _Quantity2_SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Quantity2 = v;
                }
                private static void _Quantity2_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.Quantity2_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, string>.Entry
                    MAGed = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, string>.Entry(
                        "MAGed",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MAGed_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MAGed_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MAGed_ComputeValue);
                private static void _MAGed_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MAGed, sf);
                }
                private static void _MAGed_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MAGed_Validate(r);
                }
                private static string _MAGed_ComputeValue(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    string value = default(string);
                    e.MAGed_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.ActionsItem>.Entry
                    ActionsItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.ActionsItem>.Entry(
                        "ActionsItem",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_GetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_SetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_Refresh,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._ActionsItem_OnValueChanged);
                private static void _ActionsItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.ActionsItem>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ActionsItem, sf);
                }
                private static bool _ActionsItem_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.ActionsItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActionsItem_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActionsItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ActionsItem_GetCoreImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ActionsItem;
                }
                private static global::LightSwitchApplication.ActionsItem _ActionsItem_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ActionsItem, global::LightSwitchApplication.ActionsItem.DetailsClass>(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ActionsItem, ref d._ActionsItem);
                }
                private static void _ActionsItem_SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, global::LightSwitchApplication.ActionsItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ActionsItem, ref d._ActionsItem, (i, ev) => i.ActionsItem = ev, v);
                }
                private static void _ActionsItem_Refresh(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.ActionsItem, ref d._ActionsItem);
                }
                private static void _ActionsItem_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.ActionsItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Entry
                    MatsAndGoodsItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Entry(
                        "MatsAndGoodsItem",
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Stub,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Validate,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_GetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_SetImplementationValue,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_Refresh,
                        global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties._MatsAndGoodsItem_OnValueChanged);
                private static void _MatsAndGoodsItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Data> c, global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MatsAndGoodsItem, sf);
                }
                private static bool _MatsAndGoodsItem_ComputeIsReadOnly(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    bool result = false;
                    e.MatsAndGoodsItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _MatsAndGoodsItem_Validate(global::LightSwitchApplication.ActionsFillerItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MatsAndGoodsItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _MatsAndGoodsItem_GetCoreImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MatsAndGoodsItem;
                }
                private static global::LightSwitchApplication.MatsAndGoodsItem _MatsAndGoodsItem_GetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.MatsAndGoodsItem, global::LightSwitchApplication.MatsAndGoodsItem.DetailsClass>(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem);
                }
                private static void _MatsAndGoodsItem_SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d, global::LightSwitchApplication.MatsAndGoodsItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem, (i, ev) => i.MatsAndGoodsItem = ev, v);
                }
                private static void _MatsAndGoodsItem_Refresh(global::LightSwitchApplication.ActionsFillerItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ActionsFillerItem.DetailsClass.PropertySetProperties.MatsAndGoodsItem, ref d._MatsAndGoodsItem);
                }
                private static void _MatsAndGoodsItem_OnValueChanged(global::LightSwitchApplication.ActionsFillerItem e)
                {
                    e.MatsAndGoodsItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, decimal>.Data _Quantity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data _PricePerUnit;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data _PriceTotal;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data _Quantity1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::System.Nullable<decimal>>.Data _Quantity2;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, string>.Data _MAGed;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.ActionsItem>.Data _ActionsItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ActionsFillerItem, global::LightSwitchApplication.ActionsFillerItem.DetailsClass, global::LightSwitchApplication.MatsAndGoodsItem>.Data _MatsAndGoodsItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
